expanded class SB_WAPI_FONT_OUTPUT_PRECISION

feature -- Class data

   OUT_DEFAULT_PRECIS   : INTEGER is 0;
   OUT_STRING_PRECIS    : INTEGER is 1;
   OUT_CHARACTER_PRECIS : INTEGER is 2;
   OUT_STROKE_PRECIS    : INTEGER is 3;
   OUT_TT_PRECIS        : INTEGER is 4;
   OUT_DEVICE_PRECIS    : INTEGER is 5;
   OUT_RASTER_PRECIS    : INTEGER is 6;
   OUT_TT_ONLY_PRECIS   : INTEGER is 7;
   OUT_OUTLINE_PRECIS   : INTEGER is 8;

end
