expanded class SB_WAPI_FONT_OUTPUT_PRECISION

feature -- Class data

   OUT_DEFAULT_PRECIS   : INTEGER = 0;
   OUT_STRING_PRECIS    : INTEGER = 1;
   OUT_CHARACTER_PRECIS : INTEGER = 2;
   OUT_STROKE_PRECIS    : INTEGER = 3;
   OUT_TT_PRECIS        : INTEGER = 4;
   OUT_DEVICE_PRECIS    : INTEGER = 5;
   OUT_RASTER_PRECIS    : INTEGER = 6;
   OUT_TT_ONLY_PRECIS   : INTEGER = 7;
   OUT_OUTLINE_PRECIS   : INTEGER = 8;

end
